baseURL = "/"
languageCode = "en-us"
title = ""
description = "Hot garbage fire of epic proportions."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "Journey Code"
    logo = "favicon/owl.png"
    twitterAuthor = "@natedayta"
    githubUsername = "nathancday"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/Classes/"
    name = "Classes"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:james.lee@sombr.net"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Journeycode"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://facebook.com/james.lee.228/"
    name = "fab fa-facebook"
    weight = 3